"use client";

import { useState } from "react";
import { getLegalShield, generateLegalNotice, type AwbiGuideline, type LegalNoticeRequest } from "@/lib/triageApi";

// ── Service definition ─────────────────────────────────────────────────────────
const SERVICES = [
  {
    id: "pet_rights",
    icon: "gavel",
    label: "Pet Rights",
    sublabel: "AWBI Legal Shield",
    description: "Know your rights. Get a legal notice PDF for your RWA.",
    color: "bg-secondary-container",
    textColor: "text-secondary-dim",
    action: "open_legal",
  },
  {
    id: "emergency_vet",
    icon: "emergency",
    label: "Emergency Vet",
    sublabel: "24/7 Bangalore",
    description: "Connect to the nearest 24/7 emergency veterinary clinic.",
    color: "bg-primary-container/20",
    textColor: "text-primary",
    action: "call_vet",
  },
  {
    id: "senior_care",
    icon: "elderly",
    label: "Senior Care",
    sublabel: "Silver Paws",
    description: "Assess your senior pet's risk for palliative care referral.",
    color: "bg-tertiary-container/30",
    textColor: "text-tertiary-dim",
    action: "senior_risk",
  },
  {
    id: "health_vault",
    icon: "folder_shared",
    label: "Health Vault",
    sublabel: "Transfer Records",
    description: "Securely transfer your pet's biological identity to a guardian.",
    color: "bg-surface-container-high",
    textColor: "text-on-surface",
    action: "health_vault",
  },
  {
    id: "triage",
    icon: "medical_services",
    label: "Symptom Triage",
    sublabel: "AI Powered",
    description: "Describe symptoms and get an immediate AI triage assessment.",
    color: "bg-error-container/20",
    textColor: "text-error",
    action: "triage",
  },
  {
    id: "register",
    icon: "verified",
    label: "BBMP Register",
    sublabel: "Official Docs",
    description: "Get guidance on BBMP pet registration in Bangalore.",
    color: "bg-outline-variant/30",
    textColor: "text-on-surface",
    action: "bbmp",
  },
];

// ── PDF Generation using jsPDF ─────────────────────────────────────────────────
async function generateNoticePDF(noticeText: string, citedGuidelines: string[]) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // Header
  doc.setFillColor(166, 51, 0);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(255, 239, 235);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("PetSentinel Legal Shield", 14, 12);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("AWBI-Compliant Legal Notice — Bangalore / BBMP Jurisdiction", 14, 20);

  // Notice body
  doc.setTextColor(78, 33, 30);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const lines = doc.splitTextToSize(noticeText.trim(), 180);
  let y = 36;
  for (const line of lines) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, 14, y);
    y += 5;
  }

  // Guidelines footer
  if (y > 240) { doc.addPage(); y = 20; }
  y += 6;
  doc.setDrawColor(166, 51, 0);
  doc.line(14, y, 196, y);
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.text("Laws & Guidelines Cited:", 14, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  for (const g of citedGuidelines) {
    doc.text(`• ${g}`, 16, y);
    y += 5;
  }

  // Watermark
  doc.setTextColor(200, 200, 200);
  doc.setFontSize(8);
  doc.text("Generated by PetSentinel | Not a substitute for professional legal advice", 14, 290);

  doc.save("PetSentinel_Legal_Notice.pdf");
}

// ── Legal Modal ────────────────────────────────────────────────────────────────
function LegalModal({ onClose }: { onClose: () => void }) {
  const [step, setStep] = useState<"guidelines" | "form" | "generating" | "done">("guidelines");
  const [guidelines, setGuidelines] = useState<AwbiGuideline[]>([]);
  const [loadingGuidelines, setLoadingGuidelines] = useState(false);
  const [form, setForm] = useState<Partial<LegalNoticeRequest>>({});
  const [error, setError] = useState<string | null>(null);

  async function loadGuidelines() {
    setLoadingGuidelines(true);
    try {
      const data = await getLegalShield();
      setGuidelines(data.guidelines);
      setStep("guidelines");
    } catch {
      setError("Could not connect to Legal Shield API. Ensure backend is running.");
    } finally {
      setLoadingGuidelines(false);
    }
  }

  // Auto-load on mount
  if (guidelines.length === 0 && !loadingGuidelines && step === "guidelines" && !error) {
    loadGuidelines();
  }

  async function handleGeneratePDF() {
    const required: (keyof LegalNoticeRequest)[] = [
      "owner_name", "owner_address", "owner_contact",
      "rwa_name", "rwa_address", "pin_code",
      "pet_name", "species", "pet_age"
    ];
    for (const k of required) {
      if (!form[k]) {
        setError(`Please fill in: ${k.replace("_", " ")}`);
        return;
      }
    }
    setError(null);
    setStep("generating");
    try {
      const res = await generateLegalNotice(form as LegalNoticeRequest);
      await generateNoticePDF(res.notice_text, res.guidelines_cited);
      setStep("done");
    } catch (e) {
      setError(e instanceof Error ? e.message : "PDF generation failed");
      setStep("form");
    }
  }

  return (
    <div className="fixed inset-0 z-50 bg-on-surface/40 backdrop-blur-sm flex items-end md:items-center justify-center p-4">
      <div className="bg-surface-container-lowest rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-[0_40px_80px_rgba(0,0,0,0.2)]">
        {/* Modal header */}
        <div className="sticky top-0 bg-surface-container-lowest border-b border-outline-variant/20 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="material-symbols-outlined text-secondary-dim" style={{ fontVariationSettings: "'FILL' 1" }}>gavel</span>
            <h2 className="font-headline font-bold text-on-surface">Pet Rights — Legal Shield</h2>
          </div>
          <button onClick={onClose} className="text-on-surface-variant hover:text-on-surface">
            <span className="material-symbols-outlined">close</span>
          </button>
        </div>

        <div className="p-6">
          {error && (
            <p className="text-error text-sm font-body mb-4 flex items-center gap-2 bg-error/10 p-3 rounded-lg">
              <span className="material-symbols-outlined text-[18px]">error</span> {error}
            </p>
          )}

          {/* Guidelines tab */}
          {step === "guidelines" && (
            <div className="space-y-6">
              <p className="text-sm font-body text-on-surface-variant">
                Under Indian law, RWAs <strong>cannot ban pets</strong>. These laws protect you in Bangalore.
              </p>
              {loadingGuidelines ? (
                <div className="flex flex-col items-center gap-3 py-10">
                  <div className="w-10 h-10 border-4 border-secondary-container border-t-secondary rounded-full animate-spin" />
                  <p className="text-sm font-body text-on-surface-variant">Loading AWBI guidelines...</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {guidelines.map((g) => (
                    <details key={g.id} className="bg-surface-container-low rounded-xl overflow-hidden group">
                      <summary className="px-5 py-4 cursor-pointer list-none flex items-center justify-between font-label text-on-surface text-sm">
                        <div className="flex items-center gap-3">
                          <span className="material-symbols-outlined text-secondary-dim text-[18px]">policy</span>
                          <span>{g.title}</span>
                        </div>
                        <span className="material-symbols-outlined text-on-surface-variant group-open:rotate-180 transition-transform">expand_more</span>
                      </summary>
                      <div className="px-5 pb-4 space-y-2 text-sm font-body text-on-surface-variant">
                        <p>{g.summary}</p>
                        <p className="text-secondary-dim font-label flex items-center gap-1">
                          <span className="material-symbols-outlined text-[14px]">arrow_right</span>
                          {g.actionable}
                        </p>
                        <div className="flex flex-wrap gap-2 mt-2">
                          {g.legal_sections.map((s) => (
                            <span key={s} className="bg-surface-container px-2 py-0.5 rounded-full text-xs font-label text-on-surface-variant">{s}</span>
                          ))}
                        </div>
                      </div>
                    </details>
                  ))}
                </div>
              )}
              <button
                onClick={() => setStep("form")}
                className="w-full bg-secondary text-on-secondary py-3 rounded-xl font-headline font-bold flex items-center justify-center gap-2 hover:bg-secondary-dim transition-colors"
              >
                <span className="material-symbols-outlined">picture_as_pdf</span>
                Generate Legal Notice PDF
              </button>
            </div>
          )}

          {/* Form tab */}
          {step === "form" && (
            <div className="space-y-4">
              <p className="text-sm font-body text-on-surface-variant mb-2">Fill in your details to generate a personalised legal notice.</p>
              {(["owner_name", "owner_address", "owner_contact", "rwa_name", "rwa_address", "pin_code", "pet_name", "species", "pet_age", "bbmp_reg"] as const).map((field) => (
                <div key={field}>
                  <label className="block text-xs font-label text-on-surface-variant uppercase tracking-wider mb-1">
                    {field.replace(/_/g, " ")}
                  </label>
                  <input
                    type="text"
                    value={(form as Record<string, string>)[field] ?? ""}
                    onChange={(e) => setForm((f) => ({ ...f, [field]: e.target.value }))}
                    className="w-full bg-surface-container-low border-b-2 border-outline-variant/40 focus:border-secondary text-on-surface py-2 px-3 focus:outline-none transition-colors font-body text-sm"
                    placeholder={field === "pin_code" ? "560001" : field === "species" ? "Dog" : ""}
                  />
                </div>
              ))}
              <div className="flex gap-3 pt-2">
                <button onClick={() => setStep("guidelines")} className="flex-1 border border-outline-variant text-on-surface-variant py-3 rounded-xl text-sm font-label hover:bg-surface-container transition-colors">Back</button>
                <button onClick={handleGeneratePDF} className="flex-1 bg-secondary text-on-secondary py-3 rounded-xl font-headline font-bold flex items-center justify-center gap-2 hover:bg-secondary-dim transition-colors">
                  <span className="material-symbols-outlined text-[18px]">download</span>
                  Download PDF
                </button>
              </div>
            </div>
          )}

          {step === "generating" && (
            <div className="flex flex-col items-center py-16 gap-4">
              <div className="w-14 h-14 border-4 border-secondary-container border-t-secondary rounded-full animate-spin" />
              <p className="font-headline text-on-surface">Generating Legal Notice...</p>
            </div>
          )}

          {step === "done" && (
            <div className="flex flex-col items-center py-10 gap-4 text-center">
              <div className="w-20 h-20 bg-secondary-container rounded-full flex items-center justify-center">
                <span className="material-symbols-outlined text-4xl text-secondary-dim" style={{ fontVariationSettings: "'FILL' 1" }}>check_circle</span>
              </div>
              <h3 className="font-headline font-bold text-xl text-on-surface">PDF Downloaded</h3>
              <p className="text-sm font-body text-on-surface-variant max-w-sm">Your legal notice has been generated. Print, sign in blue ink, and send via Registered Post to your RWA.</p>
              <button onClick={onClose} className="mt-2 bg-secondary text-on-secondary px-6 py-3 rounded-xl font-label hover:bg-secondary-dim transition-colors">Done</button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ── Main ServicesGrid ──────────────────────────────────────────────────────────
export default function ServicesGrid() {
  const [showLegal, setShowLegal] = useState(false);

  function handleServiceClick(action: string) {
    if (action === "open_legal") {
      setShowLegal(true);
    } else if (action === "call_vet") {
      window.open("tel:+918022221188", "_self");
    } else if (action === "bbmp") {
      window.open("https://bbmp.gov.in/pets", "_blank");
    }
    // senior_risk, health_vault, triage handled by parent via mode switching
  }

  return (
    <>
      {showLegal && <LegalModal onClose={() => setShowLegal(false)} />}

      <section className="px-4 md:px-8 pt-8 pb-4">
        <h2 className="text-2xl font-headline font-bold text-on-surface mb-6 flex items-center gap-2">
          <span className="material-symbols-outlined text-tertiary-dim">apps</span>
          Services
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
          {SERVICES.map((svc) => (
            <button
              key={svc.id}
              id={`service-${svc.id}`}
              onClick={() => handleServiceClick(svc.action)}
              className="text-left bg-surface-container-lowest p-5 rounded-xl shadow-[0_4px_20px_rgba(0,0,0,0.05)] border border-outline-variant/10 hover:shadow-[0_8px_30px_rgba(0,0,0,0.1)] hover:-translate-y-0.5 active:scale-95 transition-all group"
            >
              <div className={`w-11 h-11 ${svc.color} rounded-xl flex items-center justify-center mb-3 group-hover:scale-110 transition-transform`}>
                <span className={`material-symbols-outlined ${svc.textColor} text-[22px]`} style={{ fontVariationSettings: "'FILL' 1" }}>
                  {svc.icon}
                </span>
              </div>
              <p className="font-headline font-bold text-on-surface text-sm leading-tight">{svc.label}</p>
              <p className="text-xs font-label text-on-surface-variant mt-0.5 mb-2">{svc.sublabel}</p>
              <p className="text-xs font-body text-on-surface-variant leading-relaxed">{svc.description}</p>
            </button>
          ))}
        </div>
      </section>
    </>
  );
}
